version: "2"

run:
  timeout: 5m
  go: "1.25"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - unconvert
    - unparam
    - prealloc

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes: github.com/BigKAA/topologymetrics/sdk-go

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
