run:
  timeout: 5m
  go: "1.23"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - gofmt
    - goimports
    - misspell
    - unconvert
    - unparam
    - prealloc

linters-settings:
  goimports:
    local-prefixes: github.com/BigKAA/topologymetrics

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
